import Head from "next/head";
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';
import {
    CoinbaseWalletAdapter,
    GlowWalletAdapter,
    PhantomWalletAdapter,
    SlopeWalletAdapter,
    SolflareWalletAdapter,
    SolletExtensionWalletAdapter,
    SolletWalletAdapter,
    TorusWalletAdapter,
    TokenaryWalletAdapter,
} from '@solana/wallet-adapter-wallets';

import { clusterApiUrl } from '@solana/web3.js';
import { useMemo } from 'react';
require('@solana/wallet-adapter-react-ui/styles.css');
import Navbar from "./Navbar";

const App = ({ children, pageProps }) => {
    const network = WalletAdapterNetwork.Devnet;
    const endpoint = useMemo(() => clusterApiUrl(network), [network]);

    const wallets = useMemo(
        () => [
            new SolletWalletAdapter(),
            new SolletExtensionWalletAdapter(),
            new TokenaryWalletAdapter(),
            new SolflareWalletAdapter(),
            new SlopeWalletAdapter(),
            new PhantomWalletAdapter(),
            new TorusWalletAdapter(),
            new GlowWalletAdapter(),
            new CoinbaseWalletAdapter(),
        ],
        []
    );

    return (
        <div>

            <Head>
                <title>ScanCure</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

                <ConnectionProvider endpoint={endpoint}>
                    <WalletProvider wallets={wallets} autoConnect>
                        <WalletModalProvider>
                            <Navbar />
                            {children}
                        </WalletModalProvider>
                    </WalletProvider>
                </ConnectionProvider>

        </div>

    );
};

export default App;